version: '3.7'
services:
    rabbitmq:
      image: rabbitmq:3.8.3-management-alpine
      hostname: rabbitmq
      environment:
        RABBITMQ_DEFAULT_USE: user
        RABBITMQ_DEFAULT_PASS: pass

      ports:
        - 5672:5672
        - 15672:15672

